### ISSUE TITLE
화면 확대시 배경 이미지를 벗어나는 이슈

### ISSUE THREAD

**Issue by SuwonLee-SNU** [SuwonLee-SNU/dashboard#11]
화면을 확대해서 컨텐츠가 화면 밖으로 밀려나면, 배경 이미지를 벗어나서 보기 싫게 나옴.

**Comment by SuwonLee-SNU** [comment]
## 개발 항목
- body 의 overflow 값을 주는 방식으로 해결함.
```css
body {
    overflow: hidden;
}
```
